spring:
  application:
    name: medibear

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: Userpassword

server:
  port: 8080
  address: 0.0.0.0

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.app.medibear.**.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null


cors:
  allowed:
    origins: "http://localhost:5173"
  fastapi:
    url: "http://localhost:8000"
