server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: medibear

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-withered-darkness-a1tmyqae-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_dan9lDkwSP5X

  jpa:
    hibernate:
      ddl-auto: update   # (개발 중) create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


cors:
  allowed:
    origins: http://192.168.0.32:5173
fastapi:
  url: http://127.0.0.1:8000

jwt:
  secret: medibear
  expiration-time: 1000000000