spring:
  application:
    name: CropAIProject

#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name:

server:
  port: 8080
  address: 0.0.0.0

#mybatis:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: com.example.todolistreact.**.dto
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: null


cors:
  allowed:
    origins: "http://localhost:5173"